# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86c8bb5ac5ff6dce6500e3f0c8aaef8e525ab53996a15f1fd0a7c28404244ebf353fe00d2e0a01873bd6069452a10013a72086f73ee74c80ba63fd9e7f639040

test:
  secret_key_base: dd93da9708f6c9c5b59754ec148199b3131d5fc9e17dc8a5cd4f5802c0c911752a4343082733223bb2dea01518528c1a13970dc256972adf20987451893559ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
